// Mock data for development and testing

import { ORDER_STATUSES, USER_ROLES } from './constants';

export const mockUser = {
  id: 'user-1',
  phoneNumber: '+2348012345678',
  email: 'chinedu.okafor@example.com',
  firstName: 'Chinedu',
  lastName: 'Okafor',
  role: USER_ROLES.CUSTOMER,
  address: '15 Adeniran Ogunsanya, Surulere, Lagos',
  isActive: true,
  isVerified: true,
  createdAt: new Date('2024-01-15'),
};

export const mockOrders = [
  {
    id: 'order-1',
    orderNumber: 'FC-20250121-0047',
    customerId: 'user-1',
    customerName: 'Chinedu Okafor',
    serviceType: 'basic_wash_iron',
    status: 'WASHING',
    items: [
      { id: 'item-1', name: 'Shirt - White', quantity: 2, unitPrice: 500, totalPrice: 1000 },
      { id: 'item-2', name: 'Trousers - Blue', quantity: 1, unitPrice: 500, totalPrice: 500 },
    ],
    subtotal: 1500,
    deliveryFee: 0,
    expressFee: 0,
    discount: 0,
    totalAmount: 1500,
    isPickup: true,
    isDelivery: false,
    pickupAddress: '15 Adeniran Ogunsanya, Surulere, Lagos',
    pickupDate: new Date('2025-01-21T10:30:00'),
    pickupTimeSlot: '10:00-12:00',
    estimatedReady: new Date('2025-01-23T17:00:00'),
    notes: 'Remove stain on collar',
    createdAt: new Date('2025-01-21T08:15:00'),
  },
  {
    id: 'order-2',
    orderNumber: 'FC-20250121-0045',
    customerId: 'user-1',
    customerName: 'Chinedu Okafor',
    serviceType: 'dry_clean',
    status: 'READY',
    items: [
      { id: 'item-3', name: 'Suit (2-piece)', quantity: 1, unitPrice: 2000, totalPrice: 2000 },
      { id: 'item-4', name: 'Jacket', quantity: 2, unitPrice: 1000, totalPrice: 2000 },
      { id: 'item-5', name: 'Tie', quantity: 2, unitPrice: 300, totalPrice: 600 },
    ],
    subtotal: 4600,
    deliveryFee: 500,
    expressFee: 0,
    discount: 0,
    totalAmount: 5100,
    isPickup: true,
    isDelivery: true,
    pickupAddress: '15 Adeniran Ogunsanya, Surulere, Lagos',
    pickupDate: new Date('2025-01-18T09:00:00'),
    pickupTimeSlot: '09:00-11:00',
    deliveryAddress: '15 Adeniran Ogunsanya, Surulere, Lagos',
    deliveryDate: new Date('2025-01-20T14:00:00'),
    deliveryTimeSlot: '14:00-16:00',
    estimatedReady: new Date('2025-01-20T14:00:00'),
    notes: '',
    createdAt: new Date('2025-01-18T07:30:00'),
  },
  {
    id: 'order-3',
    orderNumber: 'FC-20250121-0043',
    customerId: 'user-1',
    customerName: 'Chinedu Okafor',
    serviceType: 'express',
    status: 'DELIVERED',
    items: [
      { id: 'item-6', name: 'Shirt', quantity: 3, unitPrice: 800, totalPrice: 2400 },
      { id: 'item-7', name: 'Trousers', quantity: 2, unitPrice: 800, totalPrice: 1600 },
    ],
    subtotal: 4000,
    deliveryFee: 500,
    expressFee: 2000,
    discount: 0,
    totalAmount: 4500,
    isPickup: true,
    isDelivery: true,
    pickupAddress: '15 Adeniran Ogunsanya, Surulere, Lagos',
    pickupDate: new Date('2025-01-19T08:00:00'),
    pickupTimeSlot: '08:00-10:00',
    deliveryAddress: '15 Adeniran Ogunsanya, Surulere, Lagos',
    deliveryDate: new Date('2025-01-19T18:00:00'),
    deliveryTimeSlot: '17:00-19:00',
    estimatedReady: new Date('2025-01-19T18:00:00'),
    completedAt: new Date('2025-01-19T18:15:00'),
    notes: 'Express service - same day delivery',
    rating: 5,
    createdAt: new Date('2025-01-19T07:00:00'),
  },
];

export const mockStaffUser = {
  id: 'staff-1',
  phoneNumber: '+2348023456789',
  email: 'tunde.bakare@freshclean.com',
  firstName: 'Tunde',
  lastName: 'Bakare',
  role: USER_ROLES.STAFF,
  branchId: 'branch-1',
  branchName: 'Main Branch',
  isActive: true,
  ordersCompleted: 156,
  averageRating: 4.8,
};

export const mockStaffTasks = [
  {
    id: 'order-4',
    orderNumber: 'FC-20250121-0047',
    customerName: 'Chinedu Okafor',
    status: 'WASHING',
    items: [
      { name: 'Shirt - White', quantity: 2 },
      { name: 'Trousers - Blue', quantity: 1 },
    ],
    priority: 'normal',
    receivedAt: new Date('2025-01-21T10:30:00'),
    notes: 'Remove stain on collar',
  },
  {
    id: 'order-5',
    orderNumber: 'FC-20250121-0046',
    customerName: 'Amina Yusuf',
    status: 'READY',
    items: [
      { name: 'Dress - Red', quantity: 2 },
      { name: 'Jacket', quantity: 1 },
      { name: 'Scarf', quantity: 1 },
    ],
    priority: 'high',
    receivedAt: new Date('2025-01-21T09:15:00'),
    notes: '',
  },
  {
    id: 'order-6',
    orderNumber: 'FC-20250121-0045',
    customerName: 'Tunde Bakare',
    status: 'DELAYED',
    items: [
      { name: 'Native Wear - Aso Oke', quantity: 1 },
      { name: 'Cap', quantity: 1 },
    ],
    priority: 'urgent',
    receivedAt: new Date('2025-01-20T14:00:00'),
    notes: 'Stain not completely removed - needs re-processing',
    hasIssue: true,
    issueType: 'STAIN_NOT_REMOVED',
  },
];

export const mockAdminData = {
  overview: {
    todayOrders: 47,
    todayRevenue: 285000,
    onTimeRate: 94.2,
    averageRating: 4.7,
    activeStaff: 3,
    readyForDelivery: 8,
    delayedOrders: 3,
    complaints: 2,
  },
  weeklyOrders: [
    { day: 'Mon', orders: 65 },
    { day: 'Tue', orders: 72 },
    { day: 'Wed', orders: 68 },
    { day: 'Thu', orders: 80 },
    { day: 'Fri', orders: 85 },
    { day: 'Sat', orders: 52 },
    { day: 'Sun', orders: 28 },
  ],
  recentOrders: [
    {
      orderNumber: 'FC-20250121-0047',
      customerName: 'Chinedu Okafor',
      status: 'WASHING',
      items: 3,
      createdAt: new Date('2025-01-21T10:30:00'),
    },
    {
      orderNumber: 'FC-20250121-0046',
      customerName: 'Amina Yusuf',
      status: 'READY',
      items: 5,
      createdAt: new Date('2025-01-21T09:15:00'),
    },
    {
      orderNumber: 'FC-20250121-0045',
      customerName: 'Tunde Bakare',
      status: 'DELAYED',
      items: 2,
      createdAt: new Date('2025-01-20T14:00:00'),
      hasIssue: true,
    },
  ],
  topStaff: [
    { name: 'Tunde Bakare', ordersCompleted: 45, rating: 4.9 },
    { name: 'Amina Yusuf', ordersCompleted: 42, rating: 4.8 },
    { name: 'Chinedu Okafor', ordersCompleted: 38, rating: 4.7 },
  ],
  alerts: [
    { type: 'warning', message: '3 delayed orders' },
    { type: 'error', message: '2 customer complaints' },
    { type: 'info', message: 'Low stock: Detergent' },
  ],
};

export const mockNotifications = [
  {
    id: 'notif-1',
    type: 'status_update',
    title: 'Order Status Updated',
    message: 'Your order FC-20250121-0047 is now being washed',
    orderId: 'order-1',
    isRead: false,
    createdAt: new Date('2025-01-21T11:00:00'),
  },
  {
    id: 'notif-2',
    type: 'promo',
    title: 'Special Offer!',
    message: 'Get 20% off on your next dry cleaning order',
    isRead: false,
    createdAt: new Date('2025-01-21T09:00:00'),
  },
  {
    id: 'notif-3',
    type: 'status_update',
    title: 'Order Ready for Pickup',
    message: 'Your order FC-20250121-0045 is ready for pickup',
    orderId: 'order-2',
    isRead: true,
    createdAt: new Date('2025-01-20T14:00:00'),
  },
];
